# Generated by Django 4.0.4 on 2022-05-05 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=253)),
                ('date_created', models.DateTimeField()),
                ('status', models.CharField(default='pending', max_length=30)),
            ],
        ),
    ]
